# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DragDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DragDemo
   pod 'Masonry', '~> 1.1.0'

end
